### ISSUE TITLE
Getting output of Gibbs energy, chemical potential, atomic mobility, etc.

### ISSUE THREAD

**Issue by richardotis** [richardotis/pycalphad#10]
From @lightinight
>Hello Otis,
>
>The pycalphad is a very interesting project. As a matter of fact, I'm writing a similiar parser to read a tdb file and output the expressions for molar Gibbs energy, chemical potential, thermodynamic factor, atomic mobility and so on. They are very essential to phase-field modeling and simulation. I wonder whether or not you are interested in such work. And I would be very appreciated if I could some contribution to such work.
>At present, I have implemented a very basic version to provide those thermodynamic and kinetic infomation for phases with a single sublattice. I have no idea how the Gibbs energy of a multi-sublattice phase should be constructed.
>
>Best wishes!
>
>Zhong JIng

**Comment by richardotis** [comment]
Hi Zhong Jing,

This is a very good exercise for learning! If you are just looking for something that works, I think pycalphad can currently do most of what you want. Check the constructor for the pycalphad.Model class. If you make a Model object called `mod`, then `print(mod.ast)` will print out a symbolic string form of the Gibbs energy. It's also possible to take arbitrary derivatives such as `print(mod.ast.diff(v.SiteFraction('BCC_A2', 0, 'FE')))` to take the symbolic derivative with respect to some site fraction.

For atomic mobility and thermodynamic factor, you can subclass the Model class to do what you want. (The TDB parser itself in principle should have no trouble with mobility data files.) Check the `Model._redlich_kister_sum()` function for how you can construct the atomic mobility and thermodynamic factor (also works for multi-sublattice systems). This is on my todo list in a couple months but probably won't make it into the first release in the next few weeks. I'd love for someone to write a DiffusionModel subclass before me though.

Feel free to use this issue to track your progress and ask questions if you decide to take it on. I'm looking for co-authors for the first pycalphad paper later this year, and a connection to phase-field modeling would be a great contribution, if you're interested in working together on it.

Have a great day!

**Comment by lightinight** [comment]
Hello Otis,

As far as I'm concerned, there are some differences between a thermodynamic and kinetic tdb file. There might be lines to specify zero volume species, like "ZEROVOLUME_SPECIES VA !". And there are additional information for a kinetic "PARAMETER", for example, "PARAMETER MQ(FCC_A1&AL,AL:VA) 298.15 -123111.6-97.34*T; 6000 N !". 

It seems that pyparsing and regular expression are used to parsed a tdb file, which I'm not very familiar with. I'm trying to read through your parser, and it might take some more time before I contrive a way to deal with a kinetic tdb file for your parser. 

When it comes to multi-sublattice phase, I wonder if you can give me instruction on how to construct the Gibbs energy of such phases. Here follows with thermodynamic infomation of an ansatz phase. Such problem has puzzled me for a long time. I would be very happy if you can inform me of some paper or publishment about this.
#####################################################
 PHASE ANSATZ % 3 1 1 1!
 CONSTITUENT ANSATZ :A,B,C,D:E,F,G:H,I: !
 
 #case 1: it seems that the order of triple interaction parameter should not be larger than 2.
 PARAMETER G(ANSATZ, A,B,C:E:H; 3) 298 100; 6000 N !
 
 #case 2:
 PARAMETER G(ANSATZ, A,B,C,D:E:H; 1) 298 100; 6000 N !
 
 #case 3:
 PARAMETER G(ANSATZ, A,B:E,F:H; 0) 298 100; 6000 N !
 PARAMETER G(ANSATZ, A,B:E,F:H; 1) 298 100; 6000 N !
 
 #case 4:
 PARAMETER G(ANSATZ, A,B:E,F:H,I; 0) 298 100; 6000 N !
 PARAMETER G(ANSATZ, A,B:E,F:H,I; 1) 298 100; 6000 N !
 
 #case 5:
 PARAMETER G(ANSATZ, A,B,C,D:E,F,G:H,I; 0) 298 100 6000 N !
####################################################

What's more, I'm worried about the permission for the usage of the format of tdb file, which is created by a commercial company. 

Have a nice day!

**Comment by richardotis** [comment]
This is a good point about the mobility syntax that I had forgotten about.

For ternary interaction parameters, the integer after the semicolon does not refer to the order of the parameter. It refers to the index of the component in the ternary interaction: 0 is the first component, 1 is the second, 2 is the third. If you only list a ternary interaction for component 0, Thermo-Calc will automatically generate the same value for components 1 and 2 to make it symmetric. Both of those aspects are not documented anywhere, from what I've seen.

Regarding permissions for the TDB format, it was originally created by SGTE and, regardless, I do not think commercial companies have had good luck claiming ownership of file formats when others seek to develop interoperable programs.

**Comment by lightinight** [comment]
Hi Otis,

A kinetic tdb file has been used to tested the parser of pycalphad. It seems that it doesn't work with with the parameter type, "MQ". It's supposed that a case keyword "MQ" can be added to the param_type. An new kind of symbol_name should be added to deal with the phase name following with "&AL", like "phase_name = Word(alphanums+'_&', min=1)". Actually, I cann't manage to make any change for the "cmd_parameter", which is a bit complicated for me at present. 

In such case, I made some changes to the _process_parameter function as following to obtain the mobility tag. (there is no doubt that a new data member, mobilitytag, should be added to _parameters of the Database class.)
######################(for _process_parameter)
def _process_parameter(targetdb, param_type, phase_name, #pylint: disable=R0913
                       constituent_array, param_order, param, ref=None):
    """
    Process the PARAMETER command.
    """
    temp = phase_name.split("&")
    phase_name = temp[0]
    mobilitytag = ""
    if(len(temp)>1):
    	mobilitytag = temp[1]
    targetdb.add_parameter(param_type, phase_name, mobilitytag, constituent_array.asList(),
                           param_order, param, ref)
######################for _parameters
new_parameter = {
            'phase_name': phase_name,
            'mobilitytag': mobilitytag,
            'constituent_array': constituent_array,
            'parameter_type': param_type,
            'parameter_order': param_order,
            'parameter': param,
            'reference': ref
        }
######################

I would like to provide a kinetic tdb sample here if you are to test it youself. But do not trust the information of this tdb file, which might be invalid.
######################
$****************************************************************************
TEMP_LIM 298.15 6000.00 !

$ ELEMENT STABLE ELEMENT REFERENCE  MASS        H298-H0     S298
ELEM VA   VACUUM                    0.0000E+00  0.0000E+00  0.0000E+00 2 !
ELEM AL   FCC_A1                    2.6982E+01  4.5773E+03  2.8322E+01 !
ELEM MG   HCP                       24.305       4998         32.671 !
ELEM SI   DIAMOND                   2.8085E+01  3.2175E+03  1.8820E+01!

DEFINE_SYSTEM_DEFAULT SPECIE 2 !
DEFAULT_COM DEF_SY_EL VA !

 PHASE FCC_A1 % 2 1 1 !
 CONSTITUENT FCC_A1 :AL,MG,SI:VA: !

TYPE_DEFINITION % SEQ * !

PARAM VS(FCC_A1) 0 1E-5; 6000 N !

ZEROVOLUME_SPECIES VA !

PARAMETER MQ(FCC_A1&AL,AL:VA) 298.15 -123111.6-97.34*T; 6000 N !

PARAMETER MQ(FCC_A1&AL,MG:VA) 298.15 -112499-81.26*T; 6000.00 N !

PARAMETER MQ(FCC_A1&AL,SI:VA) 298.15 -155634.921-81.0257*T; 6000 N !

PARAMETER MQ(FCC_A1&AL,AL,MG:VA;0) 298.15 0; 6000 N !

PARAMETER MQ(FCC_A1&AL,AL,SI:VA;0) 298.15  1846710.24; 6000 N !

PARAMETER MQ(FCC_A1&MG,AL:VA) 298.15 -121268.4-89.95*T; 6000.00 N !

PARAMETER MQ(FCC_A1&MG,MG:VA) 298.15 -112499-81.26*T; 6000.00 N !

PARAMETER MQ(FCC_A1&MG,SI:VA) 298.15 -155634.921-81.0257*T; 6000.00 N !

PARAMETER MQ(FCC_A1&MG,AL,MG:VA;0) 298.15 84924.19; 6000 N !

PARAMETER MQ(FCC_A1&MG,MG,SI:VA;0) 298.15 0; 6000.00 N !

PARAMETER MQ(FCC_A1&SI,AL:VA) 298.15 -117600-93.046*T; 6000 N !

PARAMETER MQ(FCC_A1&SI,MG:VA) 298.15 -112499-81.26*T; 6000.00 N !

PARAMETER MQ(FCC_A1&SI,SI:VA) 298.15 -155634.921-81.0257*T; 6000 N !

PARAMETER MQ(FCC_A1&SI,AL,SI:VA;0) 298.15 -152613.876; 6000 N !

PARAMETER MQ(FCC_A1&SI,MG,SI:VA;0) 298.15 0; 6000.00 N !

######################

What's more, there are some other exceptions in this tdb file which are beyond the cases in your parser. When the order of a parameter is zero, such a digit can be left out as well as the comma ";". This can be found in the manual of Thermo-Calc, "manual-tc-TC_Database_Guide.pdf". I wonder if the parser should be adapted to such cases or just let it go.

Have a nice day!

**Comment by richardotis** [comment]
Thanks for looking into this so carefully. Regarding the "&" syntax, I think I know how to adjust cmd_parameter to handle the case. I might be able to get to it this week. For the order zero parameter issue, can you open a separate issue and include a small example TDB?

**Comment by lightinight** [comment]
I might have find an alternative way to deal with the "&' syntax. Also, a new "Word" should be added.

phase_name = Word(alphanums+'_&', min=1).setParseAction(lambda t: ('&' in t[0]) and t[0].split('&') or [t[0], ''])". 

As for the order zero parameter, I'm not sure how you would like to treat it. This is the same as the case that keywords might be abbreviated, which brings so much exceptions to a standard tdb file. To modify the code and make it suitable for the case, or just command that such detailed information should not be ommited in a tdb file. 

By the way, the kinetic tdb file listed above can be used to demonstrate the case with the zero order parameter.

**Comment by zhongjingjogy** [comment]
I tested my parser with a commercial tdb file and it crashed, while it works well with your parser. I'm considering of using pyparsing now, which is very convenient to handle exceptions. I might refer to some codes in your project and I wonder if you will mind.

Thanks very much for your time!

**Comment by richardotis** [comment]
You are welcome to use the entire pycalphad package and extend/modify it any way you want. Take a look at the license included with the source code (MIT license); the terms are very permissive.

**Comment by richardotis** [comment]
Besides the mobility tag, I fixed the other TDB issues discussed in this issue, so I'm going to go ahead and close. Feel free to open a new issue if something else comes up.
