### ISSUE TITLE
Sorting elements in Redlich-Kister interaction parameters

### ISSUE THREAD

**Issue by richardotis** [richardotis/pycalphad#17]
It seems that most (all?) CALPHAD software out there is alphabetically sorting the components listed in binary (and higher-order?) interaction parameters. What this means is that, e.g., `G(LIQUID,C,W;1)` == `G(LIQUID,W,C;1)` even though they theoretically differ by a sign when the order parameter is odd (1 in this case). I haven't been able to find this documented anywhere but it has an impact on pycalphad's ability to reproduce results from the literature, e.g. the W-C diagram from Gustafson 1986, and I'm sure there are many others.

**Comment by zhongjingjogy** [comment]
Yes, it does. I manage to verify whether a self-constructed expression carries the same result result as Thermo-Calc(version p).. It comes out that the site-fraction or mole fraction in the odd order relich-kister should be placed in alphabetical order, or the difference would be larger.
