### ISSUE TITLE
 a switch in chemical potential calculation

### ISSUE THREAD

**Issue by broshe** [richardotis/pycalphad#21]
I calculated the chemical potential in of Fe in Al-Fe liquid.
Here is the code:
db = Database('alfe_sei.TDB') 
data = equilibrium(db, ['FE', 'AL'], 'LIQUID', {v.X('FE'): .2, v.T: Trange, v.P: 1e5},verbose=False)
muFe=data['MU'].sel( component='FE').data[0][0][0]
print('Mu(Fe)=',muFe)

The output is
MuFe=-133484.35563831546

Now, this is not what I got from thermo-calc with the same calculation.
Interestingly, the value of -133484.356 is the chemical potential of Al for the same conditions.
So, perhaps pycalphad somehow switched between the two potentials.

Best regards,
Eli

**Comment by richardotis** [comment]
Hi Eli, what is the value of `Trange`?

**Comment by broshe** [comment]
Sorry,
Trange=2000 (K)

**Comment by richardotis** [comment]
Okay, I can reproduce your value. Can you tell me what Thermo-Calc's value for MU(Fe) is?

**Comment by broshe** [comment]
POLY_3:s-c t=2000 x(fe)=.2 p=1e5  n=1
POLY_3:ch_st ph *=sus
POLY_3:ch_st ph liquid=ent 0
POLY_3:l-c
 T=2000, X(FE)=0.2, P=1E5, N=1
 DEGREES OF FREEDOM 0
POLY_3:c-e
 Using global minimization procedure
Calculated           137 grid points in             0 s
Found the set of lowest grid points in              0 s
 Calculated POLY solution       0 s, total time     0  s
POLY_3:show mu(fe)
* MU(FE)=-184306.01*
POLY_3:show mu(al)
 MU(AL)=-133815.12

**Comment by richardotis** [comment]
You appear to be correct. I've also checked the energy surface and the error becomes self-evident. I'll investigate this further. 
![image](https://cloud.githubusercontent.com/assets/6405510/9773119/7a29f43e-570e-11e5-9437-20ce40fb3c66.png)

**Comment by richardotis** [comment]
The overall molar energy I compute at 2000 K and X(Fe) = 0.2 is `-144066.749`. Does Thermo-Calc get close to that value? I'm trying to figure out if this issue is just a display error or if there's a more serious bug in the equilibrium engine.

**Comment by broshe** [comment]
Thermo-calc gives:
GM=-143913.3

**Comment by richardotis** [comment]
As you suggested this looks like an error with sorting component names. If you change your condition to X(AL)=0.8, which should be equivalent, the chemical potentials are now the same as Thermo-Calc and the reported energy is `-143913.2912436`. What appears to be happening is pycalphad is flipping the component names around, so the equilibrium it's reporting is for X(FE)=0.8. The result is correct, just for the wrong conditions. I will write a fix and test and ping you when the bugfix release is pushed out.

**Comment by broshe** [comment]
Thanks Richard,
I tried the calculation with x(Al)=0.8 instead of x(Fe)=.2. This gives the
correct results.
Eli

**Comment by richardotis** [comment]
@broshe pycalphad 0.2.1 has been released, which includes a fix for this issue. `pip install -U pycalphad` to update. Please let me know if this resolves your issue. (Make sure the value of `pycalphad.__version__` when you `print` it is 0.2.1, after the update.)

By the way, these are *exactly* the kinds of bugs I'm looking to find, so please keep on reporting and I'll fix them as quickly as I can.

**Comment by broshe** [comment]
Hi Richard,
I tried to install the new pycalphad
by using
pip install -U pycalphad
or
pip3 install -U pycalphad

In both cases the installation failed.
The log file is attached.
What can be done?

Thanks,
Eli
