### ISSUE TITLE
limiting the composition range of a phase

### ISSUE THREAD

**Issue by broshe** [richardotis/pycalphad#29]
Hello Richard,
I am looking for a way to make a calculation with a constraint that a certain phase can appear only at a defined composition range.
Suppose we have two phases with Gibs energy -composition curves as depicted in the attached figure.
![energy curves](https://cloud.githubusercontent.com/assets/13480270/11117287/439dbc88-8941-11e5-8421-8cc3759ce44f.png)

Suppose the overall composition is x0=0.65
An equilibrium calculation for this system would give a two-phase coexistence.
I would like to be able to constrain the calculation so that phase two cannot appear at certain compositions. For example, If I would be able to say that phase 2 cannot appear with composition x>0.6, the constrained equilibrium calculation would give a single phase equilibrium (only phase 1).
This is equivalent to adding a very large positive value to the Gibbs energy of phase 2 for x>0.6:
G2=G2+(x>0.6)*1e10.

Is there a way to do this in pycalphad?

Regards,
Eli

**Comment by richardotis** [comment]
This should be possible, though one should be careful about the physical interpretation of such a function. I'm working on developing a comprehensive fitting module so that it would be possible to fit your own energy functions to experimental data.

I haven't tested it, but I'd try something like the below snippet.
```python
from pycalphad import calculate, equilibrium, Database, Model
import pycalphad.variables as v
from sympy import Piecewise
dbf = Database('myfile.tdb')
components = ['A', 'B']
phases = ['PHASE_ONE', 'PHASE_TWO']
mod = Model(dbf, components, 'PHASE_TWO')
# Add a special contribution to the energy model for PHASE_TWO
mod.models['stability_hack'] = Piecewise(v.Y('PHASE_TWO', 0, 'A') > 0.6, 1e5, 0.)
# The 'model' keyword argument lets us use a custom model for PHASE_TWO
# Plot the Gibbs energy to check our result
# model={'PHASE_TWO': mod} means
# "For PHASE_TWO, use my special model object.
#  For all other phases, use the default Model class."
energies = calculate(dbf, components, phases, output='GM',
                     model={'PHASE_TWO': mod}, T=300, P=101325)
energies.GM.plot()

# Equilibrium calculation to verify result
eq = equilibrium(dbf, components, phases, model={'PHASE_TWO': mod},
                 {v.T: 300, v.P: 101325, v.X('A'): (0.01, 0.99, 0.1)})
```
