### ISSUE TITLE
"zip_longest" vs "izip_longest" issue

### ISSUE THREAD

**Issue by brianvanleeuwen** [richardotis/pycalphad#6]
I had to modify "itertools.zip_longest" on line 144 of "pycalphad-master\pycalphad\plot\binary.py" to "itertools.izip_longest" to work with python 2.7.8.

From the itertools documentation, it looks like maybe this is a difference between the python 2 and python 3 versions of itertools.

**Comment by brianvanleeuwen** [comment]
A simple "hack" to get around this problem:

```python
from sys import version
import itertools
if version[0]=='2':
    itertools.zip_longest=itertools.izip_longest
```

**Comment by vvasquezsj** [comment]
great work around!
