### ISSUE TITLE
TDB parser doesn't understand % symbol in component names

### ISSUE THREAD

**Issue by richardotis** [richardotis/pycalphad#9]
The parser for TDB files does not properly handle the "%" symbol in component names. This causes it to silently fail to parse CONSTITUENT commands containing these symbols, causing opaque error messages for the end user.

Workaround
-------------
Delete % symbols from component names.

Solution
---------
The parser should drop these symbols silently since pycalphad's equilibrium engine won't need hints on the starting point for energy minimization.

**Comment by lightinight** [comment]
Hello Otis,

The pycalphad is a very interesting project. As a matter of fact, I'm writing a similiar parser to read a tdb file and output the expressions for molar Gibbs energy, chemical potential, thermodynamic factor, atomic mobility and so on. They are very essential to phase-field modeling and simulation. I wonder whether or not you are interested in such work. And I would be very appreciated if I could some contribution to such work.
At present, I have implemented a very basic version to provide those thermodynamic and kinetic infomation for phases with a single sublattice. I have no idea how the Gibbs energy of a multi-sublattice phase should be constructed.

Best wishes!

Zhong JIng
